### ISSUE TITLE
Add Minimum LLAP Heap Size calc

### ISSUE THREAD

**Issue by dstreev** [dstreev/hive_llap_calculator#1]
Heap size shouldn't be less than (num of executors * 4g)

**Comment by seanorama** [comment]
Rather than being based on a percentage, or set to a minimum, could it be directly calculated:
```
llap_heapsize = num-of-executors *4GB
```

And then have the IO memory calculated as the available memory left in the container?

Is there ever any reasons to give more than num-of-executors*4GB?

**Comment by dstreev** [comment]
I've made this adjustment and it's available currently in the 'memory' branch.

The adjustment basically resets the minimum mem for the LLAP Daemon Heap to EXECUTORS * 4Gb if not met.  The config can use more, but will require that as a min.
